version: '3.9'

services:
  banking_db:
    container_name: mysql_banking
    image: mysql:8:3:0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 6906:3306
    environment:
      MYSQL_ROOT_PASSWORD: api_root
      MYSQL_USER: banking
      MYSQL_DATABASE: bank
      MYSQL_PASSWORD: api
    volumes:
      - ./docker-volumes/mysql:/var/li
